homepage: "https://github.com/tdrozdovsky/lpvs"
language: jvm
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/tdrozdovsky/lpvs"
sanitizers:
  - address
vendor_ccs:
  - "o.kopysov@samsung.com"
  - "t.drozdovsky@samsung.com"
